//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Api Documentation */
public struct JanoAPI {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    public static let version = "1.0"

    public enum Autenticación {}
    public enum Billpocket {}
    public enum ConsultaVentas {}
    public enum InfoCliente {}
    public enum Ventas {}

}
