//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension JanoPaymentservicesAPI.Reportes {

    /**
    Get ExcelReport Report  returns file id, call /reports/file/id to download
    */
    public enum BuildExcelReportUsingPOST {

        public static let service = APIService<Response>(id: "buildExcelReportUsingPOST", tag: "Reportes", method: "POST", path: "/api/servicepayment/transactionsByDate/excel/{startDateString}/{endDateString}", hasBody: false)

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** App Version */
                public var appversion: String?

                /** Device ID */
                public var deviceid: String?

                /** endDateString */
                public var endDateString: String

                /** Session Token */
                public var sessiontoken: String?

                /** startDateString */
                public var startDateString: String

                public init(appversion: String? = nil, deviceid: String? = nil, endDateString: String, sessiontoken: String? = nil, startDateString: String) {
                    self.appversion = appversion
                    self.deviceid = deviceid
                    self.endDateString = endDateString
                    self.sessiontoken = sessiontoken
                    self.startDateString = startDateString
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: BuildExcelReportUsingPOST.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(appversion: String? = nil, deviceid: String? = nil, endDateString: String, sessiontoken: String? = nil, startDateString: String) {
                let options = Options(appversion: appversion, deviceid: deviceid, endDateString: endDateString, sessiontoken: sessiontoken, startDateString: startDateString)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "endDateString" + "}", with: "\(self.options.endDateString)").replacingOccurrences(of: "{" + "startDateString" + "}", with: "\(self.options.startDateString)")
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = ReportResponse

            /** OK */
            case status200(ReportResponse)

            /** Created */
            case status201

            /** Unauthorized */
            case status401

            /** Forbidden */
            case status403

            /** Not Found */
            case status404

            public var success: ReportResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status201: return 201
                case .status401: return 401
                case .status403: return 403
                case .status404: return 404
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status201: return true
                case .status401: return false
                case .status403: return false
                case .status404: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(ReportResponse.self, from: data))
                case 201: self = .status201
                case 401: self = .status401
                case 403: self = .status403
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
